server:
  port: 8900
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

