spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}projects/personal/microservice-discovery-eureka/configuration-server/src/main/resources
server:
 port: 8888

 app:
   greet: Hello