server:
  port: 8083
  servlet:
    context-path: /reviews

spring:
  application:
    name: reviews-service
  data:
    mongodb:
      database: reviews
    rest:
      default-media-type: application/json
  datasource:
    url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysql
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


