server:
  port: 8080
  servlet:
    context-path: /books
spring:
  application:
    name: books-service
  datasource:
    url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysql
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
