server:
  port: 8080
  servlet:
    context-path: /library/books
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/books?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mysql
  jpa:
    show-sql: true

