server:
  port: 8081
  servlet:
    context-path: /library/pages
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pages?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mysql
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

application:
  page:
    text: Book\n\n%s-%s\n\nPage\n\n#%s\n\nContent\n\n%s

